# Seattle Car Accidents Analysis

## Introduction/Business Problem

As the world is growing tremendously,demands of the people also increased exponentially. Technology is one of the most important driving factor behind the growth. For ease of transportation, hybrid /electric cars were been introduced to the market which attracts the majority of the population.Therefore,more vehicles on the road leds to the drastic leap in the collision rates as well.

The Seattle government is going to prevent avoidable car accidents by employing methods that alert drivers through alert display system and police to be more careful in critical situations.In most cases, not paying enough attention during driving, drugs and alcohol or driving at very high speed for fun/competition are the main causes of occurring accidents that can be prevented by deploying harsher regulations. Besides the aforementioned causes, weather, visibility, or road conditions are the major uncontrollable factors that can be prevented by revealing hidden patterns in the data and announcing warning to the local government, police and drivers on the targeted roads.

The target audience of the project is local Seattle government, police, rescue groups and insurance organisation as well. This model results will provide them to make insightful decisions for reducing the number of accidents for the city.

## Data Set

The data was collected by the Seattle Police Department and  Accident Traffic Records Department from 2004 to present.
The data consists of 37 independent variables and 194,673 rows. The dependent variable, “SEVERITYCODE”, contains numbers that correspond to different levels of severity caused by an accident from 0 to 4.
Severity codes are as follows:
* 0: No Probability Clear Conditions)
* 1: Very Low Probability — Chance or Property Damage
* 2: Low Probability — Chance of Injury
* 3: Mild Probability — Chance of Serious Injury
* 4: High Probability — Chance of Fatality

Furthermore, because of the existence of null values in some records, the data needs to be preprocessed before any further processing.
Among all the features, I believe the following features have the most influence in the accuracy of the predictions:
* “WEATHER”,
* “ROADCOND”,
* “LIGHTCOND”

The target variable is “SEVERITYCODE”.

Please find the category wise results in case of weather/Road Cond/Light Cond as below.

## Data PreProcessing - Feature Selection and Extraction

In [106]:
import pandas as pd
df = pd.read_csv("Data-Collisions.csv")
df.shape

(194673, 38)

In [107]:
df.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY REPORTNO  \
0             2 -122.323148  47.703140         1    1307       1307  3502005   
1             1 -122.347294  47.647172         2   52200      52200  2607959   
2             1 -122.334540  47.607871         3   26700      26700  1482393   
3             1 -122.334803  47.604803         4    1144       1144  3503937   
4             2 -122.306426  47.545739         5   17700      17700  1807429   

    STATUS      ADDRTYPE   INTKEY  ... ROADCOND                LIGHTCOND  \
0  Matched  Intersection  37475.0  ...      Wet                 Daylight   
1  Matched         Block      NaN  ...      Wet  Dark - Street Lights On   
2  Matched         Block      NaN  ...      Dry                 Daylight   
3  Matched         Block      NaN  ...      Dry                 Daylight   
4  Matched  Intersection  34387.0  ...      Wet                 Daylight   

  PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0           NaN         NaN      NaN         10   
1           NaN   6354039.0      NaN         11   
2           NaN   4323031.0      NaN         32   
3           NaN         NaN      NaN         23   
4           NaN   4028032.0      NaN         10   

                                          ST_COLDESC  SEGLANEKEY  \
0                                  Entering at angle           0   
1  From same direction - both going straight - bo...           0   
2                             One parked--one moving           0   
3                   From same direction - all others           0   
4                                  Entering at angle           0   

   CROSSWALKKEY  HITPARKEDCAR  
0             0             N  
1             0             N  
2             0             N  
3             0             N  
4             0             N  

[5 rows x 38 columns]

In [108]:
df["SEVERITYCODE"].value_counts()

1    136485
2     58188
Name: SEVERITYCODE, dtype: int64

In [57]:
df.groupby(["WEATHER"])["SEVERITYCODE"].value_counts(normalize=True)

WEATHER                   SEVERITYCODE
Blowing Sand/Dirt         1               0.732143
                          2               0.267857
Clear                     1               0.677509
                          2               0.322491
Fog/Smog/Smoke            1               0.671353
                          2               0.328647
Other                     1               0.860577
                          2               0.139423
Overcast                  1               0.684456
                          2               0.315544
Partly Cloudy             2               0.600000
                          1               0.400000
Raining                   1               0.662815
                          2               0.337185
Severe Crosswind          1               0.720000
                          2               0.280000
Sleet/Hail/Freezing Rain  1               0.752212
                          2               0.247788
Snowing                   1               0

In [18]:
df["WEATHER"].value_counts()

Clear                       111135
Raining                      33145
Overcast                     27714
Unknown                      15091
Snowing                        907
Other                          832
Fog/Smog/Smoke                 569
Sleet/Hail/Freezing Rain       113
Blowing Sand/Dirt               56
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

In [19]:
df["ROADCOND"].value_counts()

Dry               124510
Wet                47474
Unknown            15078
Ice                 1209
Snow/Slush          1004
Other                132
Standing Water       115
Sand/Mud/Dirt         75
Oil                   64
Name: ROADCOND, dtype: int64

In [21]:
df["LIGHTCOND"].value_counts()

Daylight                    116137
Dark - Street Lights On      48507
Unknown                      13473
Dusk                          5902
Dawn                          2502
Dark - No Street Lights       1537
Dark - Street Lights Off      1199
Other                          235
Dark - Unknown Lighting         11
Name: LIGHTCOND, dtype: int64

In [128]:
from sklearn.utils import resample
pre_df_maj = df[df.SEVERITYCODE==1]
pre_df_min = df[df.SEVERITYCODE==2]

pre_df_maj_dsample = resample(pre_df_maj,
                              replace=False,
                              n_samples=10000,
                              random_state=123)

pre_df_min_sample = resample(pre_df_min,replace = False,n_samples = 10000,random_state=123)
balanced_df = pd.concat([pre_df_maj_dsample, pre_df_min_sample])

balanced_df.SEVERITYCODE.value_counts()

2    10000
1    10000
Name: SEVERITYCODE, dtype: int64

In [187]:
balanced_df.head(5)
balanced_df.shape

df_Seattle = balanced_df[["WEATHER","ROADCOND","LIGHTCOND"]]


In [188]:
df_Seattle.dropna(inplace = True)
df_Seattle.shape

C:\Users\S00250\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


(19510, 3)

In [189]:
df_Seattle = pd.concat([df_Seattle,pd.get_dummies(balanced_df["WEATHER"])], axis=1)

df_Seattle.head()

WEATHER ROADCOND LIGHTCOND  Blowing Sand/Dirt  Clear  Fog/Smog/Smoke  \
4   Raining      Wet  Daylight                  0      0               0   
21    Clear      Dry  Daylight                  0      1               0   
24    Clear      Dry  Daylight                  0      1               0   
40    Clear      Dry  Daylight                  0      1               0   
54    Clear      Dry  Daylight                  0      1               0   

    Other  Overcast  Partly Cloudy  Raining  Severe Crosswind  \
4       0         0              0        1                 0   
21      0         0              0        0                 0   
24      0         0              0        0                 0   
40      0         0              0        0                 0   
54      0         0              0        0                 0   

    Sleet/Hail/Freezing Rain  Snowing  Unknown  
4                          0        0        0  
21                         0        0        0  
24                         0        0        0  
40                         0        0        0  
54                         0        0        0

In [191]:
df_Seattle.drop(['Unknown'], axis = 1,inplace=True)
df_Seattle.drop(["WEATHER"],axis =1 , inplace = True)

In [192]:
df_Seattle.shape

(20000, 12)

In [193]:
df_Seattle = pd.concat([df_Seattle,pd.get_dummies(balanced_df["ROADCOND"])], axis=1)
df_Seattle.head(5)


ROADCOND LIGHTCOND  Blowing Sand/Dirt  Clear  Fog/Smog/Smoke  Other  \
4       Wet  Daylight                  0      0               0      0   
21      Dry  Daylight                  0      1               0      0   
24      Dry  Daylight                  0      1               0      0   
40      Dry  Daylight                  0      1               0      0   
54      Dry  Daylight                  0      1               0      0   

    Overcast  Partly Cloudy  Raining  Severe Crosswind  ...  Snowing  Dry  \
4          0              0        1                 0  ...        0    0   
21         0              0        0                 0  ...        0    1   
24         0              0        0                 0  ...        0    1   
40         0              0        0                 0  ...        0    1   
54         0              0        0                 0  ...        0    1   

    Ice  Oil  Other  Sand/Mud/Dirt  Snow/Slush  Standing Water  Unknown  Wet  
4     0    0      0              0           0               0        0    1  
21    0    0      0              0           0               0        0    0  
24    0    0      0              0           0               0        0    0  
40    0    0      0              0           0               0        0    0  
54    0    0      0              0           0               0        0    0  

[5 rows x 21 columns]

In [195]:
df_Seattle.drop(['Unknown'], axis = 1,inplace=True)
df_Seattle.drop(["ROADCOND"],axis =1 , inplace = True)
df_Seattle.shape

(20000, 19)

In [196]:
df_Seattle = pd.concat([df_Seattle,pd.get_dummies(balanced_df["LIGHTCOND"])], axis=1)
df_Seattle.shape

(20000, 28)

In [198]:
df_Seattle.drop(['Unknown'], axis = 1,inplace=True)
df_Seattle.drop(["LIGHTCOND"],axis =1 , inplace = True)
df_Seattle.head()

Blowing Sand/Dirt  Clear  Fog/Smog/Smoke  Other  Overcast  Partly Cloudy  \
4                   0      0               0      0         0              0   
21                  0      1               0      0         0              0   
24                  0      1               0      0         0              0   
40                  0      1               0      0         0              0   
54                  0      1               0      0         0              0   

    Raining  Severe Crosswind  Sleet/Hail/Freezing Rain  Snowing  ...  \
4         1                 0                         0        0  ...   
21        0                 0                         0        0  ...   
24        0                 0                         0        0  ...   
40        0                 0                         0        0  ...   
54        0                 0                         0        0  ...   

    Standing Water  Wet  Dark - No Street Lights  Dark - Street Lights Off  \
4                0    1                        0                         0   
21               0    0                        0                         0   
24               0    0                        0                         0   
40               0    0                        0                         0   
54               0    0                        0                         0   

    Dark - Street Lights On  Dark - Unknown Lighting  Dawn  Daylight  Dusk  \
4                         0                        0     0         1     0   
21                        0                        0     0         1     0   
24                        0                        0     0         1     0   
40                        0                        0     0         1     0   
54                        0                        0     0         1     0   

    Other  
4       0  
21      0  
24      0  
40      0  
54      0  

[5 rows x 26 columns]

In [199]:
y_seattle = balanced_df["SEVERITYCODE"].values
y_seattle[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

# Normalize Data

In [200]:
from sklearn import preprocessing
X= df_Seattle
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

C:\Users\S00250\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\S00250\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype uint8 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[-0.02121798, -1.17646691, -0.05439419, -0.06052579, -0.41231198,
        -0.00707124,  2.15447185, -0.00707124, -0.02121798, -0.06094047,
        -1.36202184, -0.08212912, -0.01224837, -0.0273964 , -0.01414355,
        -0.06297352, -0.02450225,  1.71015987, -0.08304966, -0.0776931 ,
        -0.57303933, -0.01414355, -0.11043991,  0.78845764, -0.17930845,
        -0.03001351],
       [-0.02121798,  0.85000266, -0.05439419, -0.06052579, -0.41231198,
        -0.00707124, -0.46415088, -0.00707124, -0.02121798, -0.06094047,
         0.73420262, -0.08212912, -0.01224837, -0.0273964 , -0.01414355,
        -0.06297352, -0.02450225, -0.58474065, -0.08304966, -0.0776931 ,
        -0.57303933, -0.01414355, -0.11043991,  0.78845764, -0.17930845,
        -0.03001351],
       [-0.02121798,  0.85000266, -0.05439419, -0.06052579, -0.41231198,
        -0.00707124, -0.46415088, -0.00707124, -0.02121798, -0.06094047,
         0.73420262, -0.08212912, -0.01224837, -0.0273964 , -0.01414355,
       

In [201]:
y = y_seattle
y[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

# Classification

We are using the training set to identify accruate model using following algorithm
* K Nearest Neighbor(KNN)
* Decision Tree
* Logistic Regression

## K Nearest Neighbor(KNN)

In [202]:
# We split the X into train and test to find the best k
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (14000, 26) (14000,)
Test set: (6000, 26) (6000,)


In [203]:
# Modeling
from sklearn.neighbors import KNeighborsClassifier
k = 3
#Train Model and Predict  
kNN_model = KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
kNN_model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [204]:
yhat = kNN_model.predict(X_test)
yhat[0:5]

array([1, 1, 1, 2, 1], dtype=int64)

In [206]:
import numpy as np
Ks=20
mean_acc=np.zeros((Ks-1))
std_acc=np.zeros((Ks-1))
ConfustionMx=[];
for n in range(1,Ks):
    
    #Train Model and Predict  
    kNN_model = KNeighborsClassifier(n_neighbors=n).fit(X_train,y_train)
    yhat = kNN_model.predict(X_test)
    
    
    mean_acc[n-1]=np.mean(yhat==y_test);
    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])
mean_acc

array([0.50283333, 0.51516667, 0.51516667, 0.5145    , 0.50866667,
       0.517     , 0.50833333, 0.51466667, 0.5105    , 0.51416667,
       0.50933333, 0.51066667, 0.51183333, 0.5145    , 0.5215    ,
       0.51516667, 0.51966667, 0.52083333, 0.52      ])

In [207]:
print( "The best accuracy was with", mean_acc.max(), "with k=", mean_acc.argmax()+1) 

The best accuracy was with 0.5215 with k= 15


In [214]:
# Modeling Rerun the model with best K
from sklearn.neighbors import KNeighborsClassifier
k = 15
#Train Model and Predict  
kNN_model = KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
kNN_model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=15, p=2,
           weights='uniform')

In [215]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
knn_yhat = kNN_model.predict(X_test)
print("KNN Jaccard index: %.2f" % jaccard_similarity_score(y_test, knn_yhat))
print("KNN F1-score: %.2f" % f1_score(y_test, knn_yhat, average='weighted') )

KNN Jaccard index: 0.52
KNN F1-score: 0.52


## Decision Tree

In [216]:
from sklearn.tree import DecisionTreeClassifier
DT_model = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
DT_model.fit(X_train,y_train)
DT_model

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [217]:
yhat = DT_model.predict(X_test)
yhat

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [218]:
DT_yhat = DT_model.predict(X_test)
print("DT Jaccard index: %.2f" % jaccard_similarity_score(y_test, DT_yhat))
print("DT F1-score: %.2f" % f1_score(y_test, DT_yhat, average='weighted') )

DT Jaccard index: 0.52
DT F1-score: 0.46


## Logistic Regression

In [219]:
from sklearn.linear_model import LogisticRegression
LR_model = LogisticRegression(C=0.01).fit(X_train,y_train)
LR_model

C:\Users\S00250\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [220]:
yhat = LR_model.predict(X_test)
yhat

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [221]:
LR_yhat = LR_model.predict(X_test)
LR_yhat_prob = LR_model.predict_proba(X_test)
print("LR Jaccard index: %.2f" % jaccard_similarity_score(y_test, LR_yhat))
print("LR F1-score: %.2f" % f1_score(y_test, LR_yhat, average='weighted') )
print("LR LogLoss: %.2f" % log_loss(y_test, LR_yhat_prob))

LR Jaccard index: 0.52
LR F1-score: 0.44
LR LogLoss: 0.69
